# Generated by Django 4.0 on 2022-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzaapp', '0002_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('contactNo', models.IntegerField(max_length=8)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('peopleno', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'TableBook',
                'verbose_name_plural': 'TableBooks',
            },
        ),
    ]
