# Generated by Django 4.0 on 2022-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzaapp', '0003_tablebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebook',
            name='contactNo',
            field=models.IntegerField(),
        ),
    ]
