# Generated by Django 4.0 on 2022-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzaapp', '0004_alter_tablebook_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebook',
            name='contactNo',
            field=models.CharField(max_length=8),
        ),
    ]
