# Generated by Django 4.0 on 2022-01-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzaapp', '0005_alter_tablebook_contactno'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('location', models.CharField(max_length=90)),
                ('pizzatype', models.CharField(choices=[('vegetarian', 'vegetarian'), ('Non-vegetarian', 'Non-vegetarian')], max_length=50)),
                ('platesno', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
            ],
            options={
                'verbose_name': 'OrderPizza',
                'verbose_name_plural': 'OrderPizzas',
            },
        ),
        migrations.AlterField(
            model_name='tablebook',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tablebook',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
